# Generated by Django 3.0.2 on 2020-01-12 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendar',
            fields=[
                ('google_calendar_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleEvent',
            fields=[
                ('iCalUID', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timeZone', models.CharField(blank=True, max_length=255)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('google_calendar_event_etag', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_calendar_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google-django.GoogleCalendar', verbose_name='GoogleCalendar')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleClientOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_access_token', models.CharField(default='', max_length=100, verbose_name='Google Access Token')),
                ('google_refresh_token', models.CharField(default='', max_length=100, verbose_name='Google Refresh Token')),
                ('google_client_id', models.CharField(default='', max_length=100, verbose_name='Google Client ID')),
                ('google_client_secret', models.CharField(default='', max_length=100, verbose_name='Google Client Secret')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'CPSS Google Client Setting',
                'verbose_name_plural': 'CPSS Google Client Settings',
                'db_table': 'cpss_google_settings',
            },
        ),
        migrations.AddField(
            model_name='googlecalendar',
            name='google_calendar_integration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='google-django.GoogleClientOption'),
        ),
        migrations.AddField(
            model_name='googlecalendar',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site'),
        ),
    ]
